# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ArmaBase <- function(mat_1, mat_2) {
    .Call(`_matrixProduct_ArmaBase`, mat_1, mat_2)
}

ArmaColumnRow <- function(mat_1, mat_2) {
    .Call(`_matrixProduct_ArmaColumnRow`, mat_1, mat_2)
}

RcppOpenMP <- function(mat_1, mat_2, t = 1L) {
    .Call(`_matrixProduct_RcppOpenMP`, mat_1, mat_2, t)
}

RcppParallelLoop <- function(mat_1, mat_2) {
    .Call(`_matrixProduct_RcppParallelLoop`, mat_1, mat_2)
}

